#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Runs CI in the docker dev container.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    ./docker/build
    docker run --rm \
        --entrypoint /src/stactools-nexrad-l3/scripts/cibuild \
        stactools-nexrad-l3-dev:latest
fi
