FROM stactools-nexrad-l3:latest

RUN conda install -c conda-forge pandoc

COPY . /src/stactools-nexrad-l3
RUN pip install -r /src/stactools-nexrad-l3/requirements-dev.txt
WORKDIR /src/stactools-nexrad-l3
